export const generatedAt = '2026-03-13T21:55:00+02:00';

export const projectSections = [
  {
    id: 'browser',
    title: 'Browser-ready apps and sites',
    description: 'Conventional browser projects that should run locally once their normal web stack is available.',
  },
  {
    id: 'platform',
    title: 'Browser-ready with specialized platform tooling',
    description: 'Still web-facing, but dependent on Wrangler, Shopify CLI, Playwright, or similar platform-specific flows.',
  },
  {
    id: 'docs',
    title: 'Content repos and doc systems',
    description: 'Content-first repositories that appear to feed shared documentation or navigator tooling.',
  },
  {
    id: 'static',
    title: 'Static tools and single-file sites',
    description: 'Fastest to inspect because they open directly in a browser or require only a thin local server.',
  },
  {
    id: 'native',
    title: 'Native or specialized runtime projects',
    description: 'Projects that are not normal browser apps and instead depend on Python, Xcode, Unity, or incomplete server wiring.',
  },
];

export const projectCatalog = [
  {
    name: 'EARN Ecosystem website',
    workspace: 'EARN Ecosystem website',
    category: 'browser',
    summary: 'React/Vite/Tailwind site.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Looks organized and ready for browser testing.',
    commitCount: 53,
    lastUpdated: '2026-03-13T20:38:31+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'FounderPressureTest',
    workspace: 'FounderPressureTest',
    category: 'browser',
    summary: 'Vite/React mobile-first decision game about founder pressure.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Needs a git baseline before more work piles up.',
    commitCount: null,
    lastUpdated: '2026-03-06T23:30:22+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'GearRoulette',
    workspace: 'GearRoulette',
    category: 'browser',
    summary: 'Vite/React product-discovery app for XR and creator gear.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Nothing urgent.',
    commitCount: 1,
    lastUpdated: '2026-03-06T23:31:04+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'LedgerOne',
    workspace: 'LedgerOne',
    category: 'browser',
    summary: 'Next.js/Tailwind finance app with Prisma and the noisiest active worktree in the directory.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm, Prisma, database and env setup',
    tracking: 'Git repo with heavy local drift',
    trackingState: 'tracked',
    attention: 'High',
    attentionDetail: '10 modified files and 76 untracked files make this the biggest cleanup candidate.',
    commitCount: 1,
    lastUpdated: '2026-03-13T20:17:17+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'LedgerOne/ledgerone-temp',
    workspace: 'LedgerOne/ledgerone-temp',
    category: 'browser',
    summary: 'Separate nested Next.js repo that looks like a cleaner temporary branch or alternate implementation.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Separate git repo, clean',
    trackingState: 'tracked',
    attention: 'Watch',
    attentionDetail: 'Needs a decision on whether it stays separate, merges, or gets archived.',
    commitCount: 1,
    lastUpdated: '2026-03-13T20:17:17+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'PricePilotForShopify',
    workspace: 'PricePilotForShopify',
    category: 'browser',
    summary: 'Internal Shopify pricing console built with Next.js and Shopify Admin GraphQL.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, Shopify credentials for full fidelity',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Should be versioned before more feature work lands.',
    commitCount: null,
    lastUpdated: '2026-03-13T20:39:49+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'TwitterClone',
    workspace: 'TwitterClone',
    category: 'browser',
    summary: 'Next.js/Tailwind social app with Prisma, auth, and migration-related moving parts.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, Prisma, database, auth env vars',
    tracking: 'Git repo with active local work',
    trackingState: 'tracked',
    attention: 'High',
    attentionDetail: '6 modified files and 27 untracked files, including Prisma schema and routes.',
    commitCount: 1,
    lastUpdated: '2026-03-06T12:32:47+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'cin7-product-checker',
    workspace: 'VSCode/cin7-product-checker',
    category: 'browser',
    summary: 'Vite/React app for Cin7 product checking.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Should be versioned if it is more than a one-off sandbox.',
    commitCount: null,
    lastUpdated: '2024-11-18T22:38:56+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'Cin7CorePriceAnalyzer',
    workspace: 'bolt.new/Cin7CorePriceAnalyzer',
    category: 'browser',
    summary: 'Vite/React/Tailwind analyzer app with tests configured.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Needs version control before more iteration.',
    commitCount: null,
    lastUpdated: '2024-11-18T19:37:01+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'daliso-website-backup',
    workspace: 'daliso-website-backup',
    category: 'browser',
    summary: 'Next.js backup version of the Daliso website.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Git repo with small local drift',
    trackingState: 'tracked',
    attention: 'Medium',
    attentionDetail: 'Should be explicitly kept active or archived as a snapshot.',
    commitCount: 16,
    lastUpdated: '2025-02-19T18:02:14+02:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/DJNgoma/daliso-website',
    },
  },
  {
    name: 'earnOS',
    workspace: 'earnOS',
    category: 'browser',
    summary: 'Group operating system and internal wiki hub for Exco.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev:site',
    tooling: 'Node.js, npm, Wrangler for deploys',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Looks active enough that it should be versioned.',
    commitCount: null,
    lastUpdated: '2026-03-11T15:45:30+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'test-website',
    workspace: 'test-website',
    category: 'browser',
    summary: 'Basic Next.js sandbox site.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'Medium',
    attentionDetail: 'Should be versioned if it is more than scratch space.',
    commitCount: null,
    lastUpdated: '2026-01-14T02:51:14+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'thelombardy-co-za',
    workspace: 'thelombardy-co-za',
    category: 'browser',
    summary: 'Next.js/Tailwind website with only minor local metadata drift.',
    webLabel: 'Browser-ready',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, npm',
    tracking: 'Git repo with minor workspace noise',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Only a small untracked workspace file is present.',
    commitCount: 16,
    lastUpdated: '2026-03-13T21:32:21+02:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/DJNgoma/thelombardydotcodotza',
    },
  },
  {
    name: 'agOS',
    workspace: 'EARN_Group/agOS',
    category: 'platform',
    summary: 'African Greeneurs Operating System navigator built as a static site.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm run build && npm run preview',
    tooling: 'Node.js, npm, Wrangler',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Healthy state.',
    commitCount: 33,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'atOS',
    workspace: 'EARN_Group/atOS',
    category: 'platform',
    summary: 'Entity navigator with a build-and-preview workflow driven by local scripts.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm run build && npm run preview',
    tooling: 'Node.js, npm, scripted static preview',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Healthy state.',
    commitCount: 57,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'ebsOS',
    workspace: 'EARN_Group/ebsOS',
    category: 'platform',
    summary: 'EARN Business Solutions docs and navigator site.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm run build && npm run preview',
    tooling: 'Node.js, npm, Wrangler',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Healthy state.',
    commitCount: 44,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'earn-handbook-theme',
    workspace: 'EARN_Group/earn-handbook-theme',
    category: 'platform',
    summary: 'Shared theme and browser test harness for EARN handbook sites.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm run preview or npm test',
    tooling: 'Node.js, Playwright',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Shared infrastructure with no urgent issues.',
    commitCount: 12,
    lastUpdated: '2026-03-11T17:17:27+02:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/AfricanTechno/earn-handbook-theme',
    },
  },
  {
    name: 'EmailAliasOps',
    workspace: 'EmailAliasOps',
    category: 'platform',
    summary: 'Private Cloudflare Workers admin panel for Cloudflare Email Routing aliases.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm install && npm run dev',
    tooling: 'Wrangler, Cloudflare account, D1, API creds, local .dev.vars',
    tracking: 'Git repo with uncommitted app scaffolding',
    trackingState: 'tracked',
    attention: 'High',
    attentionDetail: 'Local worktree has real app code but zero commits so far.',
    commitCount: 0,
    lastUpdated: '2026-03-13T16:02:02+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'surety',
    workspace: 'ShopifyApps/surety',
    category: 'platform',
    summary: 'Shopify embedded app built from the React Router template.',
    webLabel: 'Browser-ready with platform tooling',
    run: 'npm install && npm run dev',
    tooling: 'Node.js, Shopify CLI, dev store, tunnel/app config, likely Prisma',
    tracking: 'Git repo with uncommitted setup and app files',
    trackingState: 'tracked',
    attention: 'High',
    attentionDetail: '41 untracked files suggest setup drift that should be normalized intentionally.',
    commitCount: 0,
    lastUpdated: '2025-10-23T15:14:21+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'aghOS',
    workspace: 'EARN_Group/aghOS',
    category: 'docs',
    summary: 'AG Horticulture operating system content repo.',
    webLabel: 'Content-first',
    run: 'Shared EARN tooling flow',
    tooling: 'Shared EARN static-site tooling',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Medium',
    attentionDetail: 'Would benefit from clearer root-level preview instructions.',
    commitCount: 35,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'alpOS',
    workspace: 'EARN_Group/alpOS',
    category: 'docs',
    summary: 'African Lakeside Properties operating system content repo.',
    webLabel: 'Content-first',
    run: 'Shared EARN tooling flow',
    tooling: 'Shared EARN handbook/static-site stack',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Medium',
    attentionDetail: 'Would benefit from clearer root-level preview instructions.',
    commitCount: 37,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'EARN_Group/earnOS',
    workspace: 'EARN_Group/earnOS',
    category: 'docs',
    summary: 'EARN Group operating system content repository.',
    webLabel: 'Content-first',
    run: 'Shared EARN tooling flow',
    tooling: 'Shared EARN build process',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Medium',
    attentionDetail: 'Looks content-first rather than directly runnable from the root.',
    commitCount: 32,
    lastUpdated: '2026-03-11T18:51:14+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'GPTSnake',
    workspace: 'GPTSnake',
    category: 'static',
    summary: 'Plain HTML/CSS/JS snake game.',
    webLabel: 'Static file',
    run: 'Open index.html directly',
    tooling: 'None',
    tracking: 'Git repo with small local environment noise',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Easy cleanup only.',
    commitCount: 1,
    lastUpdated: '2026-02-05T12:04:41+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'AGNedbank2024',
    workspace: 'Heroku/AGNedbank2024',
    category: 'static',
    summary: 'PHP-based landing or microsite with index.php.',
    webLabel: 'Static-ish',
    run: 'Serve through a PHP server',
    tooling: 'PHP runtime or Heroku-style hosting flow',
    tracking: 'Git repo with Finder metadata noise',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Only Finder noise is visible right now.',
    commitCount: 2,
    lastUpdated: '2024-03-27T17:52:25+02:00',
    repo: { kind: 'local', label: 'No public repo linked' },
  },
  {
    name: 'daliso-website',
    workspace: 'daliso-website',
    category: 'static',
    summary: 'The static site behind daliso.com.',
    webLabel: 'Static site',
    run: 'Open index.html directly or deploy to the site host',
    tooling: 'None',
    tracking: 'Git repo with minor local noise',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'This is the live portfolio site and should stay clean.',
    commitCount: 31,
    lastUpdated: '2026-02-03T18:41:38+02:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/DJNgoma/daliso-website',
    },
  },
  {
    name: 'invoiceGenerator',
    workspace: 'invoiceGenerator',
    category: 'static',
    summary: 'Single-file commercial invoice HTML tool.',
    webLabel: 'Static file',
    run: 'Open the HTML file directly',
    tooling: 'None',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'Medium',
    attentionDetail: 'Should be versioned if it matters operationally.',
    commitCount: null,
    lastUpdated: '2025-11-27T18:21:11+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'rebate-growth-model',
    workspace: 'rebate-growth-model',
    category: 'static',
    summary: 'Single-file rebate and commission calculator.',
    webLabel: 'Static file',
    run: 'Open either HTML file directly',
    tooling: 'None',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'Medium',
    attentionDetail: 'Should be versioned if it continues to be used.',
    commitCount: null,
    lastUpdated: '2025-11-24T08:12:53+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'Auto-GPT',
    workspace: 'Auto-GPT',
    category: 'native',
    summary: 'Python autonomous-agent experiment, not primarily a browser product.',
    webLabel: 'Non-browser first',
    run: 'Project-specific Python commands',
    tooling: 'Python environment and likely LLM/API credentials',
    tracking: 'Git repo with small .DS_Store noise',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Mostly just Finder cleanup.',
    commitCount: 965,
    lastUpdated: '2023-04-15T02:30:17-05:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/Torantulino/Auto-GPT',
    },
  },
  {
    name: 'TestWeb',
    workspace: 'Heroku/TestWeb',
    category: 'native',
    summary: 'Node project with an Express dependency but no clear start flow.',
    webLabel: 'Probably web-capable',
    run: 'Needs a documented server entrypoint',
    tooling: 'Node.js and an actual start command',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Underspecified and not versioned.',
    commitCount: null,
    lastUpdated: '2024-03-27T17:42:55+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'FocusTimer-iOS-ReadyProject',
    workspace: 'iOSProjects/FocusTimer-iOS-ReadyProject',
    category: 'native',
    summary: 'Native iOS app project.',
    webLabel: 'Non-browser',
    run: 'Open in Xcode',
    tooling: 'Xcode and iOS simulator/device tooling',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Should be versioned if it is active work.',
    commitCount: null,
    lastUpdated: '2025-09-29T09:02:58+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
  {
    name: 'TestAlexApp',
    workspace: 'iOSProjects/TestAlexApp',
    category: 'native',
    summary: 'Native iOS app project with active local Swift edits.',
    webLabel: 'Non-browser',
    run: 'Open in Xcode',
    tooling: 'Xcode and iOS simulator/device tooling',
    tracking: 'Git repo with tracked local edits',
    trackingState: 'tracked',
    attention: 'Medium',
    attentionDetail: 'Active local development, but at least it is tracked.',
    commitCount: 1,
    lastUpdated: '2024-11-18T17:57:09+02:00',
    repo: {
      kind: 'public',
      label: 'Public repo',
      url: 'https://github.com/daliso-africantechno/TestAlexApp',
    },
  },
  {
    name: 'TestiOS18Project',
    workspace: 'iOSProjects/TestiOS18Project',
    category: 'native',
    summary: 'Native iOS app project that currently looks clean.',
    webLabel: 'Non-browser',
    run: 'Open in Xcode',
    tooling: 'Xcode and iOS simulator/device tooling',
    tracking: 'Git repo, clean',
    trackingState: 'tracked',
    attention: 'Low',
    attentionDetail: 'Nothing urgent.',
    commitCount: 1,
    lastUpdated: '2024-06-26T12:57:31+02:00',
    repo: { kind: 'private', label: 'Repo private or not public' },
  },
  {
    name: 'Unity/New Unity Project',
    workspace: 'Unity/New Unity Project',
    category: 'native',
    summary: 'Unity project that only becomes browser-runnable if exported to WebGL.',
    webLabel: 'Non-browser',
    run: 'Open in Unity',
    tooling: 'Unity Editor',
    tracking: 'Not tracked in git',
    trackingState: 'untracked',
    attention: 'High',
    attentionDetail: 'Needs a Unity-aware version control setup if it stays active.',
    commitCount: null,
    lastUpdated: '2023-08-09T23:45:10+02:00',
    repo: { kind: 'untracked', label: 'Not tracked in git' },
  },
];
