import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("css/style.css stays flattened and avoids @import request chains", () => {
  const css = read("css/style.css");
  assert.ok(
    css.startsWith("/* Generated by scripts/build-css.mjs."),
    "Expected css/style.css to be generated by the CSS bundler."
  );
  assert.doesNotMatch(css, /@import\s+url\(/, "Do not reintroduce stylesheet import chains.");
});

test("home page keeps the optimized hero and logo delivery path", () => {
  const html = read("index.html");
  assert.match(html, /logo-120\.webp/, "Home page should use the compressed shared logo asset.");
  assert.match(html, /hero-320\.webp/, "Home page should preload the modern hero image.");
  assert.match(
    html,
    /imagesrcset="\/assets\/images\/hero-320\.webp 320w, \/assets\/images\/hero-640\.webp 640w"/
  );
  assert.match(html, /<picture>/, "Home page hero should keep the picture element wrapper.");
});

test("theme runtime and blog generator keep the lightweight shared asset path", () => {
  const themeModule = read("js/modules/theme.js");
  const blogTemplate = read("scripts/blog-lib.mjs");

  assert.doesNotMatch(themeModule, /logo_white-120\.webp/, "Theme toggling should not swap in a second logo asset.");
  assert.match(blogTemplate, /logo-120\.webp/, "Generated blog pages should use the shared lightweight logo asset.");
  assert.match(blogTemplate, /meta name="color-scheme" content="light dark"/);
  assert.match(
    blogTemplate,
    /localStorage\.getItem\('theme'\)/,
    "Generated pages should bootstrap the saved theme before CSS loads."
  );
});

test("unfingerprinted CSS and JS stay revalidating instead of immutable", () => {
  const headers = read("_headers");

  assert.match(
    headers,
    /\/css\/\*\s+Cache-Control:\s+public,\s+max-age=0,\s+must-revalidate,\s+no-transform/,
    "Shared CSS should revalidate so page-specific stylesheet edits cannot get stuck behind immutable caching."
  );
  assert.doesNotMatch(
    headers,
    /\/css\/\*\s+Cache-Control:\s+public,\s+max-age=31536000,\s+immutable/,
    "Do not mark unfingerprinted CSS as immutable."
  );

  assert.match(
    headers,
    /\/js\/\*\s+Cache-Control:\s+public,\s+max-age=0,\s+must-revalidate,\s+no-transform/,
    "Shared JS should revalidate so deployed module updates cannot get stuck behind immutable caching."
  );
  assert.doesNotMatch(
    headers,
    /\/js\/\*\s+Cache-Control:\s+public,\s+max-age=31536000,\s+immutable/,
    "Do not mark unfingerprinted JS as immutable."
  );
});

test("embedded talk deck opts out of the global frame-deny header", () => {
  const headers = read("_headers");

  assert.match(
    headers,
    /\/\*\s+[\s\S]*?X-Frame-Options:\s+DENY/,
    "The default site security header should still deny framing."
  );
  assert.match(
    headers,
    /\/media\/coding-with-ai\/deck\.html\s+[\s\S]*?! X-Frame-Options\s+[\s\S]*?Content-Security-Policy:\s+frame-ancestors 'self'/,
    "The embedded deck must detach X-Frame-Options and allow same-origin framing via CSP."
  );
});
