import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

function publicShellPages() {
  const pages = [
    "index.html",
    "about/index.html",
    "work/index.html",
    "projects/index.html",
    "media/index.html",
    "media/coding-with-ai/index.html",
    "privacy/index.html",
    "support/index.html",
    "blog/index.html",
  ];
  const blogRoot = new URL("../blog/", import.meta.url);
  for (const entry of readdirSync(blogRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || ["drafts", "posts"].includes(entry.name)) {
      continue;
    }
    pages.push(`blog/${entry.name}/index.html`);
  }
  return [...new Set(pages)].sort();
}

test("css/style.css stays flattened and avoids @import request chains", () => {
  const css = read("css/style.css");
  assert.ok(
    css.startsWith("/* Generated by scripts/build-css.mjs."),
    "Expected css/style.css to be generated by the CSS bundler."
  );
  assert.doesNotMatch(css, /@import\s+url\(/, "Do not reintroduce stylesheet import chains.");
});

test("homepage uses one generated stylesheet for the critical path", () => {
  const html = read("index.html");
  const homeCss = read("css/home.css");

  assert.match(html, /\/css\/home\.css\?v=20260621-operator-preview/);
  assert.doesNotMatch(html, /\/css\/style\.css\?/, "Home should not request a second shared stylesheet.");
  assert.doesNotMatch(html, /\/css\/pages\/home\.css\?/, "Home should not request a second page stylesheet.");
  assert.match(html, /<style>[\s\S]*\.home-hero h1/, "Home should inline only the first-viewport critical CSS needed for early visual paint.");
  assert.match(html, /rel="preload" href="\/css\/home\.css\?v=20260621-operator-preview" as="style"/);
  assert.match(html, /<noscript><link rel="stylesheet" href="\/css\/home\.css\?v=20260621-operator-preview" \/><\/noscript>/);
  assert.ok(
    homeCss.startsWith("/* Generated by scripts/build-css.mjs."),
    "Expected css/home.css to be generated by the CSS bundler."
  );
  assert.match(homeCss, /\.home-hero\b/, "Home bundle should include the page-specific hero rules.");
  assert.doesNotMatch(homeCss, /@import\s+url\(/, "Do not reintroduce stylesheet import chains.");
});

test("home page keeps the optimized hero and wordmark delivery path", () => {
  const html = read("index.html");
  assert.match(html, /class="home-wordmark"/, "Home page should use the editorial text wordmark.");
  assert.match(html, /hero-320\.webp/, "Home page should preload the modern hero image.");
  assert.match(
    html,
    /imagesrcset="\/assets\/images\/hero-320\.webp 320w, \/assets\/images\/hero-640\.webp 640w"/
  );
  assert.match(html, /<picture>/, "Home page hero should keep the picture element wrapper.");
});

test("home page avoids the duplicate Inter font transfer", () => {
  const html = read("index.html");
  const fontsCss = read("css/fonts.css");

  assert.match(html, /\/assets\/fonts\/inter-400\.woff2/);
  assert.doesNotMatch(html, /\/assets\/fonts\/inter-600\.woff2/);
  assert.doesNotMatch(fontsCss, /inter-600\.woff2/);
  assert.match(html, /\/assets\/fonts\/space-grotesk-500\.woff2/);
  assert.match(fontsCss, /font-display:\s*optional/, "Custom fonts should not hold text paint hostage on slow mobile runs.");
  assert.doesNotMatch(fontsCss, /font-display:\s*swap/, "Use optional display for the critical text fonts unless there is a deliberate visual reason not to.");
});

test("theme runtime and blog generator keep the lightweight shared asset path", () => {
  const themeModule = read("js/modules/theme.js");
  const blogTemplate = read("scripts/blog-lib.mjs");

  assert.doesNotMatch(themeModule, /logo_white-120\.webp/, "Theme toggling should not swap in a second logo asset.");
  assert.doesNotMatch(blogTemplate, /logo-120\.webp/, "Generated blog pages should not regress to the old image-logo shell.");
  assert.match(blogTemplate, /class="site-wordmark"/, "Generated blog pages should use the shared operator wordmark.");
  assert.match(blogTemplate, /meta name="color-scheme" content="light dark"/);
  assert.match(
    blogTemplate,
    /localStorage\.getItem\('theme'\)/,
    "Generated pages should bootstrap the saved theme before CSS loads."
  );
});

test("public pages share the operator shell contract", () => {
  for (const page of publicShellPages()) {
    const html = read(page);
    const nav = html.match(/<nav class="navbar" aria-label="Primary">[\s\S]*?<\/nav>/)?.[0] ?? "";
    assert.ok(nav, `${page} should render the shared primary nav.`);

    if (page === "index.html") {
      assert.match(html, /<body class="home-page">/, "Home keeps its optimized home-page body contract.");
      assert.match(nav, /class="home-wordmark"/, "Home should use the operator text wordmark.");
    } else {
      assert.match(html, /<body class="[^"]*\bsite-page\b/, `${page} should carry the site-page shell class.`);
      assert.match(nav, /class="site-wordmark"/, `${page} should use the shared operator text wordmark.`);
    }

    assert.match(nav, /id="site-logo"[^>]*>daliso<\/a>/, `${page} should expose the text wordmark as #site-logo.`);
    assert.doesNotMatch(nav, /<img[^>]+id="site-logo"/, `${page} should not use the old image logo in primary nav.`);
    assert.doesNotMatch(nav, /logo-120\.webp/, `${page} should not pull the old logo asset into the primary nav.`);
    assert.match(nav, /class="theme-toggle-mark"/, `${page} should use the shared theme-toggle mark.`);
  }
});

test("unfingerprinted CSS and JS stay revalidating instead of immutable", () => {
  const headers = read("_headers");

  assert.match(
    headers,
    /\/css\/\*\s+Cache-Control:\s+public,\s+max-age=0,\s+must-revalidate/,
    "Shared CSS should revalidate so page-specific stylesheet edits cannot get stuck behind immutable caching."
  );
  assert.doesNotMatch(
    headers,
    /\/css\/\*\s+Cache-Control:\s+public,\s+max-age=31536000,\s+immutable/,
    "Do not mark unfingerprinted CSS as immutable."
  );

  assert.match(
    headers,
    /\/js\/\*\s+Cache-Control:\s+public,\s+max-age=0,\s+must-revalidate/,
    "Shared JS should revalidate so deployed module updates cannot get stuck behind immutable caching."
  );
  assert.doesNotMatch(
    headers,
    /\/js\/\*\s+Cache-Control:\s+public,\s+max-age=31536000,\s+immutable/,
    "Do not mark unfingerprinted JS as immutable."
  );
});

test("asset headers do not inherit HTML-only discovery and no-transform rules", () => {
  const headers = read("_headers");
  const middleware = read("functions/_middleware.js");
  const globalRule = headers.match(/\/\*\s+([\s\S]*?)(?=\n\n\/assets\/\*)/)[1];

  assert.doesNotMatch(globalRule, /Cache-Control:/, "HTML cache policy should be set by middleware only for HTML responses.");
  assert.doesNotMatch(globalRule, /\bLink:/, "Discovery links should stay on HTML responses, not every asset response.");
  assert.doesNotMatch(globalRule, /\bVary:\s*Accept/, "Accept negotiation should stay on HTML responses, not every asset response.");
  assert.match(middleware, /htmlCacheControl = "public, max-age=0, must-revalidate, no-transform"/);
  assert.match(middleware, /htmlDiscoveryLinks/);
});

test("embedded talk deck opts out of the global frame-deny header", () => {
  const headers = read("_headers");

  assert.match(
    headers,
    /\/\*\s+[\s\S]*?X-Frame-Options:\s+DENY/,
    "The default site security header should still deny framing."
  );
  assert.match(
    headers,
    /\/media\/coding-with-ai\/deck\s+[\s\S]*?! X-Frame-Options\s+[\s\S]*?Content-Security-Policy:\s+frame-ancestors 'self'/,
    "The extensionless embedded deck route must detach X-Frame-Options and allow same-origin framing via CSP."
  );
  assert.match(
    headers,
    /\/media\/coding-with-ai\/deck\.html\s+[\s\S]*?! X-Frame-Options\s+[\s\S]*?Content-Security-Policy:\s+frame-ancestors 'self'/,
    "The HTML deck route should keep the same frame policy for direct requests and redirects."
  );
});

test("robots.txt keeps current AI crawler access explicit", () => {
  const robots = read("robots.txt");
  const expectedAgents = [
    "GPTBot",
    "OAI-SearchBot",
    "ChatGPT-User",
    "ClaudeBot",
    "Claude-SearchBot",
    "Claude-User",
    "HermesAgent",
    "Hermes-Agent",
    "PerplexityBot",
    "Perplexity-User",
  ];

  assert.match(robots, /Content-Signal:\s*ai-train=yes,\s*search=yes,\s*ai-input=yes/);
  for (const agent of expectedAgents) {
    assert.match(
      robots,
      new RegExp(`User-agent:\\s*${agent}\\s+Allow:\\s*/`),
      `Expected robots.txt to explicitly allow ${agent}.`
    );
  }
});
