import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const cssDir = path.join(repoRoot, "css");
const outputPath = path.join(cssDir, "style.css");
const homeOutputPath = path.join(cssDir, "home.css");
const sourceFiles = [
  "fonts.css",
  "base.css",
  "layout.css",
  "components.css",
  "animations.css",
];

function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

function renderCssBundle(contents) {
  return [
    "/* Generated by scripts/build-css.mjs. Edit the source files in css/ instead. */",
    minifyCss(contents.join("\n")),
    "",
  ].join("\n");
}

export async function buildCssBundle() {
  const contents = await Promise.all(
    sourceFiles.map(async (fileName) => readFile(path.join(cssDir, fileName), "utf8")),
  );

  const homeCss = await readFile(path.join(cssDir, "pages", "home.css"), "utf8");
  const output = renderCssBundle(contents);
  const homeOutput = renderCssBundle([...contents, homeCss]);

  await writeFile(outputPath, output, "utf8");
  await writeFile(homeOutputPath, homeOutput, "utf8");
  return [outputPath, homeOutputPath];
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  await buildCssBundle().catch((error) => {
    console.error("Failed to build css/style.css.", error);
    process.exitCode = 1;
  });
}
