import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const cssDir = path.join(repoRoot, "css");
const outputPath = path.join(cssDir, "style.css");
const sourceFiles = [
  "fonts.css",
  "base.css",
  "layout.css",
  "components.css",
  "animations.css",
];

export async function buildCssBundle() {
  const contents = await Promise.all(
    sourceFiles.map(async (fileName) => readFile(path.join(cssDir, fileName), "utf8")),
  );

  const output = [
    "/* Generated by scripts/build-css.mjs. Edit the source files in css/ instead. */",
    ...contents.map((content) => content.trim()),
    "",
  ].join("\n\n");

  await writeFile(outputPath, output, "utf8");
  return outputPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  await buildCssBundle().catch((error) => {
    console.error("Failed to build css/style.css.", error);
    process.exitCode = 1;
  });
}
